### ISSUE TITLE
Extract data to database

### ISSUE THREAD

**Issue by LuigiMaestrelli** [Developer66/open-elevation#14]
First, great job updating this project.

Is it possible to read all the data from the tif file and import to a database?
I'm trying to import to create a more complex query.

**Comment by Developer66** [comment]
Hey, 
to my knowledge importing the ftf file to a database is not possible. 

You can maybe (not the good way) write a small script, for example:

      doublewidthMap = 43.0002; // Tft image Range
      double heightMap = 49.0005;
      double steps = 0.00001; // Mesh Size

      for (double w = 0; w < width; w = w + steps) {
        for (double h = 0; h < height; h = h + steps) {
          //Query data[w][h] and write to a database
        }
      }

This is only a short example and need a better implementation ;)... If you find a better way you can maybe add the code to the project using a merge.
