### ISSUE TITLE
Error: 404 Not Found

### ISSUE THREAD

**Issue by rabimans** [Developer66/open-elevation#17]
I am new to Python
after multiple times doing this and that, i was able to run dataset.
but trying to run **python3 server.py** gave me  below error. P.S i have changed the ip from 0.0.0.0:10000 to 127.0.0.1:10000

**Sorry, the requested URL 'http://127.0.0.1:10000/' caused an error:

Not found: '/'   **

could someone please shade a light on this. 

Thank you

**Comment by Developer66** [comment]
Hey,
have you alle requirements installed? Can you post your console output when you start the server.py

Have you tried a url like this
`http://0.0.0.0:10000/api/v1/lookup?locations=48.179138,10.703618`

Ip 0.0.0.0 and 127.0.0.1 sould be the same

**Comment by rabimans** [comment]
i changed the ip to 0.0.0.0.
output of python3 server.py is 
Bottle v0.12.13 server starting up (using GunicornServer(workers=4))...
Listening on http://0.0.0.0:10000/
Hit Ctrl-C to quit.

[2020-09-15 20:12:20 +0545] [11178] [INFO] Starting gunicorn 19.7.1
[2020-09-15 20:12:20 +0545] [11178] [INFO] Listening at: http://0.0.0.0:10000 (11178)
[2020-09-15 20:12:20 +0545] [11178] [INFO] Using worker: sync
/usr/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  return io.open(fd, *args, **kwargs)
[2020-09-15 20:12:21 +0545] [11185] [INFO] Booting worker with pid: 11185
[2020-09-15 20:12:21 +0545] [11186] [INFO] Booting worker with pid: 11186
[2020-09-15 20:12:21 +0545] [11187] [INFO] Booting worker with pid: 11187
[2020-09-15 20:12:21 +0545] [11188] [INFO] Booting worker with pid: 11188


i tried the url as you mentioned above, but its not responding.

Thank you

**Comment by Developer66** [comment]
Mhm... 

Can you post a picture of your folder Sturcture?

I tried it a few minutes ago and: Not found: '/' **. Is a correct output when you dont specific a url.
But the log seems okay, so with the information you gave me i can say that it sould work.

Is a json file in the datadir generated? Are the files correctly placed in the data dir?

**Comment by rabimans** [comment]
i think its resolved. 
http://0.0.0.0:10000/api/v1/lookup?locations=48.179138,10.703618

i got reply as
{"results": [{"latitude": 48.179138, "longitude": 10.703618, "elevation": 549}]}

:)

thanks

**Comment by Developer66** [comment]
That looks good ;)

What was the problem if anyone has the same he can look at this issue

**Comment by rabimans** [comment]
yea sure. i was just trying to get reply from 0.0.0.0:10000.. which shows 404.
but when i tried with this http://0.0.0.0:10000/api/v1/lookup?locations=48.179138,10.703618 url, i got the reply.

Pointers:
>i manually edited requirement.txt gdal version to 3.0.4 then only i was able to install Gdal.
