### ISSUE TITLE
open-elevation working but not reachable from anywhere but local

### ISSUE THREAD

**Issue by Revoola** [Developer66/open-elevation#18]
I tried for days with the original open-elevation, learned a lot but never successfully got things running, I then found your fork and after reimaging my server I managed to get all installed and working pretty quickly… So THANK YOU. My python server works and listens and returns correct information when I use Curl locally (only on http.... not on https) ie after I have ssh'd into the box...   but it will not work from outside... so I am assuming it must be my web server config I believe?   I will continue to try getting this to work over the web, but wonder if there is anything obvious I might be missing.
When I try from a terminal (not logged into the server) I get the following. 

curl http://xx.xx.xx.xxx:10000/api/v1/lookup?locations=48.179138,10.703618
zsh: no matches found: http://xx.xx.xx.xxx:10000/api/v1/lookup?locations=48.179138,10.703618

**Comment by Developer66** [comment]
Hey,
happy to hear that everything works fine.

Normaly when you want to acess the server outside your network you have to unlock the port in your router. Ustage in local network area should work and is default configured by your router.

Do you want to acess the server of the outside of your network?

Developer66

**Comment by Revoola** [comment]
Thank you for your quick response my server is hosted outside of my network and I want to access it directly from my App and when I finally realised I had a glitch in ism's Firewall settings I was able to access it with curl http. , cannot get https working but really not that bothered about that , so thank you for your help, now I am off to experiment with hosting different datasets.

**Comment by Developer66** [comment]
Have fun and good luck for your further programms.
