### ISSUE TITLE
Autorun server.py after server reboots

### ISSUE THREAD

**Issue by rabimans** [Developer66/open-elevation#19]
Hi,
So i am able to get response from http://0.0.0.0:10000/api/v1/lookup?locations=48.179138,10.703618.

i am trying to setup this in my server. i used server ip instead of 0.0.0.0 and got the response too.

But my question is, if i reboot the server, i need to manually restart server.py application every time. is there any solution that it starts itself after every reboot? i am using apache webserver.

Thank you

**Comment by Developer66** [comment]
Please have look at "5." at "How to install" 

There is the autostart service setup descripted... you may adapt this for your Apache webserver.

**Comment by rabimans** [comment]
Sorry, i didnt get it. 5?

**Comment by rabimans** [comment]
i think its #4

**Comment by rabimans** [comment]
unfortunately it didnt work. i am digging more onto this anyway.

**Comment by Developer66** [comment]
The autostart script is tested on Ubuntu 18.04 - 20.04 and works. 

Your desciption of your system is not detail and seems not to be the same as I use. At the moment i can not give you any help.
Maybe you give a better desctiption of your setup
