### ISSUE TITLE
Python process wont start

### ISSUE THREAD

**Issue by nravanelli** [Developer66/open-elevation#4]
Sorry to open another issue on the same day... I am unable to get the server.py to initiate. Here is my open-elevation status results:

```
Apr 10 14:20:05 nr systemd[1]: open-elevation.service: Unit entered failed state.
Apr 10 14:20:05 nr systemd[1]: open-elevation.service: Failed with result 'exit-code'.
Apr 10 14:20:06 nr systemd[1]: open-elevation.service: Service hold-off time over, scheduling restart.
Apr 10 14:20:06 nr systemd[1]: Stopped Open-Elevation Server.
Apr 10 14:20:06 nr systemd[1]: open-elevation.service: Start request repeated too quickly.
Apr 10 14:20:06 nr systemd[1]: Failed to start Open-Elevation Server.
Apr 10 14:20:06 nr systemd[1]: open-elevation.service: Unit entered failed state.
Apr 10 14:20:06 nr systemd[1]: open-elevation.service: Failed with result 'start-limit-hit'.

```

and here is my open-elevation.service file:

```
[Unit]
Description=Open-Elevation Server
After=network.target

[Service]
Type=simple
User=opene
WorkingDirectory=/home/opene
ExecStart=/usr/bin/env python /home/opene/open-elevation/server.py
Restart=always
RestartSec=1

[Install]
WantedBy=multi-user.target
```

I have made both of them executable too (chmod +x) and that was not the issue...

**Comment by Developer66** [comment]
Hey,
can you add the log when you run the server.py manually using: `python server.py`.

I think the error is here: `WorkingDirectory=/home/opene` the WorkingDirectory should be: `WorkingDirectory=/home/opene/open-elevation/`

Hope this helps

**Comment by nravanelli** [comment]
Problem solved... dependencies were not installing for python correctly. All is working sound now, thank you for your hard work!

**Comment by Developer66** [comment]
No problem. Have fun:smile:

**Comment by rabimans** [comment]
unfortunately it didnt work. i am digging more onto this anyway.
